//
//  SignUpPresenter.swift
//  ReusableComponentsWrapUp
//
//  Created by Alejandro Orozco Builes on 4/9/19.
//  Copyright (c) 2019 Alejandro Orozco Builes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUpPresentationLogic
{
  func presentSignUpForm(formFields: [UIFormElement])
}

class SignUpPresenter: SignUpPresentationLogic
{
  weak var viewController: SignUpDisplayLogic?
  
  func presentSignUpForm(formFields: [UIFormElement]) {
    viewController?.displaySignUpForm(formFields: formFields)
  }
}
