//
//  SignUpViewController.swift
//  ReusableComponentsWrapUp
//
//  Created by Alejandro Orozco Builes on 4/9/19.
//  Copyright (c) 2019 Alejandro Orozco Builes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUpDisplayLogic: class
{
  func displaySignUpForm(formFields: [UIFormElement])
}

class SignUpViewController: UIViewController, SignUpDisplayLogic
{
  var interactor: SignUpBusinessLogic?
  var router: (NSObjectProtocol & SignUpRoutingLogic & SignUpDataPassing)?

  // MARK: Object lifecycle
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  private func setup()
  {
    let viewController = self
    let interactor = SignUpInteractor()
    let presenter = SignUpPresenter()
    let router = SignUpRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }

  @IBOutlet weak var tableView: UITableView!

  private var tableViewDataSources: [TableViewDataSource] = []
  
  // MARK: View lifecycle
  override func viewDidLoad()
  {
    super.viewDidLoad()
    tableView.rowHeight = UITableView.automaticDimension
    interactor?.createSignUpForm()
  }

  func displaySignUpForm(formFields: [UIFormElement]) {
    let formDataSource = UIFormDataSource<MyAppTextField>(formFields, tableView: tableView)
    tableViewDataSources.append(formDataSource)
    tableView.reloadData()
  }
}

extension SignUpViewController: UITableViewDataSource, UITableViewDelegate {

  func numberOfSections(in tableView: UITableView) -> Int {
    return tableViewDataSources.count
  }

  func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
    let dataSource = tableViewDataSources[section]
    return dataSource.tableView(tableView,numberOfRowsInSection: section)
  }

  func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    let dataSource = tableViewDataSources[indexPath.section]
    return dataSource.tableView(tableView, cellForRowAt: indexPath)
  }
}
